"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.duplicateFlags = exports.publishingResults = exports.publishingJobs = exports.notifications = exports.adminReviews = exports.civicReports = exports.researchSources = exports.aiResearchResults = exports.aiAnalyses = exports.problemStatusHistory = exports.problemAttachments = exports.problemLocations = exports.problems = exports.problemTypes = exports.problemCategories = void 0;
const pg_core_1 = require("drizzle-orm/pg-core");
const users_1 = require("./users");
const enums_1 = require("./enums");
exports.problemCategories = (0, pg_core_1.pgTable)('problem_categories', {
    id: (0, pg_core_1.uuid)('id').primaryKey().defaultRandom(),
    name: (0, pg_core_1.varchar)('name', { length: 100 }).notNull(),
    slug: (0, pg_core_1.varchar)('slug', { length: 100 }).notNull().unique(),
    description: (0, pg_core_1.text)('description'),
    icon: (0, pg_core_1.varchar)('icon', { length: 50 }),
    color: (0, pg_core_1.varchar)('color', { length: 20 }),
    isActive: (0, pg_core_1.boolean)('is_active').notNull().default(true),
    sortOrder: (0, pg_core_1.integer)('sort_order').notNull().default(0),
    createdAt: (0, pg_core_1.timestamp)('created_at', { withTimezone: true }).notNull().defaultNow(),
});
exports.problemTypes = (0, pg_core_1.pgTable)('problem_types', {
    id: (0, pg_core_1.uuid)('id').primaryKey().defaultRandom(),
    categoryId: (0, pg_core_1.uuid)('category_id').notNull().references(() => exports.problemCategories.id, { onDelete: 'cascade' }),
    name: (0, pg_core_1.varchar)('name', { length: 100 }).notNull(),
    slug: (0, pg_core_1.varchar)('slug', { length: 100 }).notNull(),
    description: (0, pg_core_1.text)('description'),
    isActive: (0, pg_core_1.boolean)('is_active').notNull().default(true),
    sortOrder: (0, pg_core_1.integer)('sort_order').notNull().default(0),
    createdAt: (0, pg_core_1.timestamp)('created_at', { withTimezone: true }).notNull().defaultNow(),
});
exports.problems = (0, pg_core_1.pgTable)('problems', {
    id: (0, pg_core_1.uuid)('id').primaryKey().defaultRandom(),
    civId: (0, pg_core_1.varchar)('civ_id', { length: 30 }).notNull().unique(),
    userId: (0, pg_core_1.uuid)('user_id').notNull().references(() => users_1.users.id, { onDelete: 'set null' }),
    categoryId: (0, pg_core_1.uuid)('category_id').references(() => exports.problemCategories.id, { onDelete: 'set null' }),
    typeId: (0, pg_core_1.uuid)('type_id').references(() => exports.problemTypes.id, { onDelete: 'set null' }),
    title: (0, pg_core_1.varchar)('title', { length: 255 }).notNull(),
    description: (0, pg_core_1.text)('description'),
    status: (0, enums_1.problemStatusEnum)('status').notNull().default('submitted'),
    userPriority: (0, enums_1.problemPriorityEnum)('user_priority').notNull().default('medium'),
    aiPriority: (0, enums_1.problemPriorityEnum)('ai_priority'),
    finalPriority: (0, enums_1.problemPriorityEnum)('final_priority'),
    effectivePriority: (0, enums_1.problemPriorityEnum)('effective_priority').notNull().default('medium'),
    attachmentCount: (0, pg_core_1.integer)('attachment_count').notNull().default(0),
    isDuplicate: (0, pg_core_1.boolean)('is_duplicate').notNull().default(false),
    duplicateOfId: (0, pg_core_1.uuid)('duplicate_of_id'),
    verifiedAt: (0, pg_core_1.timestamp)('verified_at', { withTimezone: true }),
    resolvedAt: (0, pg_core_1.timestamp)('resolved_at', { withTimezone: true }),
    publishedAt: (0, pg_core_1.timestamp)('published_at', { withTimezone: true }),
    createdAt: (0, pg_core_1.timestamp)('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: (0, pg_core_1.timestamp)('updated_at', { withTimezone: true }).notNull().defaultNow(),
});
exports.problemLocations = (0, pg_core_1.pgTable)('problem_locations', {
    id: (0, pg_core_1.uuid)('id').primaryKey().defaultRandom(),
    problemId: (0, pg_core_1.uuid)('problem_id').notNull().references(() => exports.problems.id, { onDelete: 'cascade' }).unique(),
    city: (0, pg_core_1.varchar)('city', { length: 100 }).notNull(),
    area: (0, pg_core_1.varchar)('area', { length: 255 }),
    address: (0, pg_core_1.text)('address'),
    latitude: (0, pg_core_1.varchar)('latitude', { length: 30 }),
    longitude: (0, pg_core_1.varchar)('longitude', { length: 30 }),
    country: (0, pg_core_1.varchar)('country', { length: 100 }).default('Pakistan'),
    createdAt: (0, pg_core_1.timestamp)('created_at', { withTimezone: true }).notNull().defaultNow(),
});
exports.problemAttachments = (0, pg_core_1.pgTable)('problem_attachments', {
    id: (0, pg_core_1.uuid)('id').primaryKey().defaultRandom(),
    problemId: (0, pg_core_1.uuid)('problem_id').notNull().references(() => exports.problems.id, { onDelete: 'cascade' }),
    fileName: (0, pg_core_1.varchar)('file_name', { length: 255 }).notNull(),
    originalName: (0, pg_core_1.varchar)('original_name', { length: 255 }).notNull(),
    mimeType: (0, pg_core_1.varchar)('mime_type', { length: 100 }).notNull(),
    fileSize: (0, pg_core_1.integer)('file_size').notNull(),
    storageKey: (0, pg_core_1.varchar)('storage_key', { length: 500 }).notNull(),
    storageUrl: (0, pg_core_1.text)('storage_url'),
    attachmentType: (0, enums_1.attachmentTypeEnum)('attachment_type').notNull(),
    createdAt: (0, pg_core_1.timestamp)('created_at', { withTimezone: true }).notNull().defaultNow(),
});
exports.problemStatusHistory = (0, pg_core_1.pgTable)('problem_status_history', {
    id: (0, pg_core_1.uuid)('id').primaryKey().defaultRandom(),
    problemId: (0, pg_core_1.uuid)('problem_id').notNull().references(() => exports.problems.id, { onDelete: 'cascade' }),
    fromStatus: (0, enums_1.problemStatusEnum)('from_status'),
    toStatus: (0, enums_1.problemStatusEnum)('to_status').notNull(),
    changedById: (0, pg_core_1.uuid)('changed_by_id').references(() => users_1.users.id, { onDelete: 'set null' }),
    notes: (0, pg_core_1.text)('notes'),
    createdAt: (0, pg_core_1.timestamp)('created_at', { withTimezone: true }).notNull().defaultNow(),
});
exports.aiAnalyses = (0, pg_core_1.pgTable)('ai_analyses', {
    id: (0, pg_core_1.uuid)('id').primaryKey().defaultRandom(),
    problemId: (0, pg_core_1.uuid)('problem_id').notNull().references(() => exports.problems.id, { onDelete: 'cascade' }).unique(),
    provider: (0, pg_core_1.varchar)('provider', { length: 50 }).notNull().default('openai'),
    model: (0, pg_core_1.varchar)('model', { length: 100 }),
    summary: (0, pg_core_1.text)('summary'),
    severityAssessment: (0, pg_core_1.text)('severity_assessment'),
    priorityRecommendation: (0, enums_1.problemPriorityEnum)('priority_recommendation'),
    categoryValidation: (0, pg_core_1.text)('category_validation'),
    evidenceAnalysis: (0, pg_core_1.text)('evidence_analysis'),
    duplicateFlag: (0, pg_core_1.boolean)('duplicate_flag').notNull().default(false),
    duplicateConfidence: (0, pg_core_1.integer)('duplicate_confidence').default(0),
    missingInformation: (0, pg_core_1.jsonb)('missing_information').$type(),
    confidenceScore: (0, pg_core_1.integer)('confidence_score').default(0),
    recommendedAction: (0, pg_core_1.text)('recommended_action'),
    rawResponse: (0, pg_core_1.jsonb)('raw_response'),
    completedAt: (0, pg_core_1.timestamp)('completed_at', { withTimezone: true }),
    createdAt: (0, pg_core_1.timestamp)('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: (0, pg_core_1.timestamp)('updated_at', { withTimezone: true }).notNull().defaultNow(),
});
exports.aiResearchResults = (0, pg_core_1.pgTable)('ai_research_results', {
    id: (0, pg_core_1.uuid)('id').primaryKey().defaultRandom(),
    problemId: (0, pg_core_1.uuid)('problem_id').notNull().references(() => exports.problems.id, { onDelete: 'cascade' }).unique(),
    backgroundInfo: (0, pg_core_1.text)('background_info'),
    possibleCauses: (0, pg_core_1.text)('possible_causes'),
    communityImpact: (0, pg_core_1.text)('community_impact'),
    relevantStatistics: (0, pg_core_1.text)('relevant_statistics'),
    similarIncidents: (0, pg_core_1.text)('similar_incidents'),
    potentialSolutions: (0, pg_core_1.text)('potential_solutions'),
    responsibleAuthority: (0, pg_core_1.text)('responsible_authority'),
    estimatedResolutionTime: (0, pg_core_1.text)('estimated_resolution_time'),
    completedAt: (0, pg_core_1.timestamp)('completed_at', { withTimezone: true }),
    createdAt: (0, pg_core_1.timestamp)('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: (0, pg_core_1.timestamp)('updated_at', { withTimezone: true }).notNull().defaultNow(),
});
exports.researchSources = (0, pg_core_1.pgTable)('research_sources', {
    id: (0, pg_core_1.uuid)('id').primaryKey().defaultRandom(),
    researchId: (0, pg_core_1.uuid)('research_id').notNull().references(() => exports.aiResearchResults.id, { onDelete: 'cascade' }),
    title: (0, pg_core_1.varchar)('title', { length: 500 }),
    url: (0, pg_core_1.text)('url'),
    summary: (0, pg_core_1.text)('summary'),
    relevanceScore: (0, pg_core_1.integer)('relevance_score'),
    createdAt: (0, pg_core_1.timestamp)('created_at', { withTimezone: true }).notNull().defaultNow(),
});
exports.civicReports = (0, pg_core_1.pgTable)('civic_reports', {
    id: (0, pg_core_1.uuid)('id').primaryKey().defaultRandom(),
    problemId: (0, pg_core_1.uuid)('problem_id').notNull().references(() => exports.problems.id, { onDelete: 'cascade' }).unique(),
    overview: (0, pg_core_1.text)('overview'),
    whyItMatters: (0, pg_core_1.text)('why_it_matters'),
    researchFindings: (0, pg_core_1.text)('research_findings'),
    severity: (0, pg_core_1.text)('severity'),
    recommendedAction: (0, pg_core_1.text)('recommended_action'),
    responsibleAuthority: (0, pg_core_1.text)('responsible_authority'),
    proposedPostContent: (0, pg_core_1.text)('proposed_post_content'),
    hashtags: (0, pg_core_1.jsonb)('hashtags').$type(),
    isAdminEdited: (0, pg_core_1.boolean)('is_admin_edited').notNull().default(false),
    adminEditedAt: (0, pg_core_1.timestamp)('admin_edited_at', { withTimezone: true }),
    adminEditedById: (0, pg_core_1.uuid)('admin_edited_by_id').references(() => users_1.users.id, { onDelete: 'set null' }),
    createdAt: (0, pg_core_1.timestamp)('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: (0, pg_core_1.timestamp)('updated_at', { withTimezone: true }).notNull().defaultNow(),
});
exports.adminReviews = (0, pg_core_1.pgTable)('admin_reviews', {
    id: (0, pg_core_1.uuid)('id').primaryKey().defaultRandom(),
    problemId: (0, pg_core_1.uuid)('problem_id').notNull().references(() => exports.problems.id, { onDelete: 'cascade' }),
    adminId: (0, pg_core_1.uuid)('admin_id').notNull().references(() => users_1.users.id, { onDelete: 'set null' }),
    action: (0, pg_core_1.varchar)('action', { length: 100 }).notNull(),
    notes: (0, pg_core_1.text)('notes'),
    priorityOverride: (0, enums_1.problemPriorityEnum)('priority_override'),
    createdAt: (0, pg_core_1.timestamp)('created_at', { withTimezone: true }).notNull().defaultNow(),
});
exports.notifications = (0, pg_core_1.pgTable)('notifications', {
    id: (0, pg_core_1.uuid)('id').primaryKey().defaultRandom(),
    userId: (0, pg_core_1.uuid)('user_id').notNull().references(() => users_1.users.id, { onDelete: 'cascade' }),
    problemId: (0, pg_core_1.uuid)('problem_id').references(() => exports.problems.id, { onDelete: 'cascade' }),
    type: (0, enums_1.notificationTypeEnum)('type').notNull(),
    title: (0, pg_core_1.varchar)('title', { length: 255 }).notNull(),
    message: (0, pg_core_1.text)('message').notNull(),
    isRead: (0, pg_core_1.boolean)('is_read').notNull().default(false),
    createdAt: (0, pg_core_1.timestamp)('created_at', { withTimezone: true }).notNull().defaultNow(),
});
exports.publishingJobs = (0, pg_core_1.pgTable)('publishing_jobs', {
    id: (0, pg_core_1.uuid)('id').primaryKey().defaultRandom(),
    problemId: (0, pg_core_1.uuid)('problem_id').notNull().references(() => exports.problems.id, { onDelete: 'cascade' }),
    triggeredById: (0, pg_core_1.uuid)('triggered_by_id').references(() => users_1.users.id, { onDelete: 'set null' }),
    platforms: (0, pg_core_1.jsonb)('platforms').$type().notNull(),
    status: (0, enums_1.publishingStatusEnum)('status').notNull().default('pending'),
    startedAt: (0, pg_core_1.timestamp)('started_at', { withTimezone: true }),
    completedAt: (0, pg_core_1.timestamp)('completed_at', { withTimezone: true }),
    createdAt: (0, pg_core_1.timestamp)('created_at', { withTimezone: true }).notNull().defaultNow(),
});
exports.publishingResults = (0, pg_core_1.pgTable)('publishing_results', {
    id: (0, pg_core_1.uuid)('id').primaryKey().defaultRandom(),
    jobId: (0, pg_core_1.uuid)('job_id').notNull().references(() => exports.publishingJobs.id, { onDelete: 'cascade' }),
    problemId: (0, pg_core_1.uuid)('problem_id').notNull().references(() => exports.problems.id, { onDelete: 'cascade' }),
    platform: (0, enums_1.publishingPlatformEnum)('platform').notNull(),
    status: (0, enums_1.publishingStatusEnum)('status').notNull().default('pending'),
    publishedUrl: (0, pg_core_1.text)('published_url'),
    errorMessage: (0, pg_core_1.text)('error_message'),
    retryCount: (0, pg_core_1.integer)('retry_count').notNull().default(0),
    publishedAt: (0, pg_core_1.timestamp)('published_at', { withTimezone: true }),
    createdAt: (0, pg_core_1.timestamp)('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: (0, pg_core_1.timestamp)('updated_at', { withTimezone: true }).notNull().defaultNow(),
});
exports.duplicateFlags = (0, pg_core_1.pgTable)('duplicate_flags', {
    id: (0, pg_core_1.uuid)('id').primaryKey().defaultRandom(),
    problemId: (0, pg_core_1.uuid)('problem_id').notNull().references(() => exports.problems.id, { onDelete: 'cascade' }),
    potentialDuplicateId: (0, pg_core_1.uuid)('potential_duplicate_id').notNull().references(() => exports.problems.id, { onDelete: 'cascade' }),
    confidenceScore: (0, pg_core_1.integer)('confidence_score').notNull(),
    reason: (0, pg_core_1.text)('reason'),
    resolvedByAdminId: (0, pg_core_1.uuid)('resolved_by_admin_id').references(() => users_1.users.id, { onDelete: 'set null' }),
    resolution: (0, pg_core_1.varchar)('resolution', { length: 50 }),
    createdAt: (0, pg_core_1.timestamp)('created_at', { withTimezone: true }).notNull().defaultNow(),
    resolvedAt: (0, pg_core_1.timestamp)('resolved_at', { withTimezone: true }),
});
//# sourceMappingURL=problems.js.map