export declare const problemCategories: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "problem_categories";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "problem_categories";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        name: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "name";
            tableName: "problem_categories";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        slug: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "slug";
            tableName: "problem_categories";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        description: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "description";
            tableName: "problem_categories";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        icon: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "icon";
            tableName: "problem_categories";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        color: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "color";
            tableName: "problem_categories";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        isActive: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "is_active";
            tableName: "problem_categories";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        sortOrder: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "sort_order";
            tableName: "problem_categories";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "problem_categories";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const problemTypes: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "problem_types";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "problem_types";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        categoryId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "category_id";
            tableName: "problem_types";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        name: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "name";
            tableName: "problem_types";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        slug: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "slug";
            tableName: "problem_types";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        description: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "description";
            tableName: "problem_types";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        isActive: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "is_active";
            tableName: "problem_types";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        sortOrder: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "sort_order";
            tableName: "problem_types";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "problem_types";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const problems: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "problems";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "problems";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        civId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "civ_id";
            tableName: "problems";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        userId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "user_id";
            tableName: "problems";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        categoryId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "category_id";
            tableName: "problems";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        typeId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "type_id";
            tableName: "problems";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        title: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "title";
            tableName: "problems";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        description: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "description";
            tableName: "problems";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        status: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "status";
            tableName: "problems";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "submitted" | "under_verification" | "ai_analysis" | "ai_research" | "verified" | "rejected" | "awaiting_approval" | "approved" | "publishing" | "published" | "in_progress" | "resolved" | "closed" | "more_info_needed";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: ["submitted", "under_verification", "ai_analysis", "ai_research", "verified", "rejected", "awaiting_approval", "approved", "publishing", "published", "in_progress", "resolved", "closed", "more_info_needed"];
            baseColumn: never;
        }, {}, {}>;
        userPriority: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "user_priority";
            tableName: "problems";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "low" | "medium" | "high" | "critical";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: ["low", "medium", "high", "critical"];
            baseColumn: never;
        }, {}, {}>;
        aiPriority: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "ai_priority";
            tableName: "problems";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "low" | "medium" | "high" | "critical";
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: ["low", "medium", "high", "critical"];
            baseColumn: never;
        }, {}, {}>;
        finalPriority: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "final_priority";
            tableName: "problems";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "low" | "medium" | "high" | "critical";
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: ["low", "medium", "high", "critical"];
            baseColumn: never;
        }, {}, {}>;
        effectivePriority: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "effective_priority";
            tableName: "problems";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "low" | "medium" | "high" | "critical";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: ["low", "medium", "high", "critical"];
            baseColumn: never;
        }, {}, {}>;
        attachmentCount: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "attachment_count";
            tableName: "problems";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        isDuplicate: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "is_duplicate";
            tableName: "problems";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        duplicateOfId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "duplicate_of_id";
            tableName: "problems";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        verifiedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "verified_at";
            tableName: "problems";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        resolvedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "resolved_at";
            tableName: "problems";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        publishedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "published_at";
            tableName: "problems";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "problems";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        updatedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "updated_at";
            tableName: "problems";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const problemLocations: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "problem_locations";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "problem_locations";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        problemId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "problem_id";
            tableName: "problem_locations";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        city: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "city";
            tableName: "problem_locations";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        area: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "area";
            tableName: "problem_locations";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        address: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "address";
            tableName: "problem_locations";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        latitude: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "latitude";
            tableName: "problem_locations";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        longitude: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "longitude";
            tableName: "problem_locations";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        country: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "country";
            tableName: "problem_locations";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "problem_locations";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const problemAttachments: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "problem_attachments";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "problem_attachments";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        problemId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "problem_id";
            tableName: "problem_attachments";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        fileName: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "file_name";
            tableName: "problem_attachments";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        originalName: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "original_name";
            tableName: "problem_attachments";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        mimeType: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "mime_type";
            tableName: "problem_attachments";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        fileSize: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "file_size";
            tableName: "problem_attachments";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        storageKey: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "storage_key";
            tableName: "problem_attachments";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        storageUrl: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "storage_url";
            tableName: "problem_attachments";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        attachmentType: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "attachment_type";
            tableName: "problem_attachments";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "image" | "document" | "other";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: ["image", "document", "other"];
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "problem_attachments";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const problemStatusHistory: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "problem_status_history";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "problem_status_history";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        problemId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "problem_id";
            tableName: "problem_status_history";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        fromStatus: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "from_status";
            tableName: "problem_status_history";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "submitted" | "under_verification" | "ai_analysis" | "ai_research" | "verified" | "rejected" | "awaiting_approval" | "approved" | "publishing" | "published" | "in_progress" | "resolved" | "closed" | "more_info_needed";
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: ["submitted", "under_verification", "ai_analysis", "ai_research", "verified", "rejected", "awaiting_approval", "approved", "publishing", "published", "in_progress", "resolved", "closed", "more_info_needed"];
            baseColumn: never;
        }, {}, {}>;
        toStatus: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "to_status";
            tableName: "problem_status_history";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "submitted" | "under_verification" | "ai_analysis" | "ai_research" | "verified" | "rejected" | "awaiting_approval" | "approved" | "publishing" | "published" | "in_progress" | "resolved" | "closed" | "more_info_needed";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: ["submitted", "under_verification", "ai_analysis", "ai_research", "verified", "rejected", "awaiting_approval", "approved", "publishing", "published", "in_progress", "resolved", "closed", "more_info_needed"];
            baseColumn: never;
        }, {}, {}>;
        changedById: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "changed_by_id";
            tableName: "problem_status_history";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        notes: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "notes";
            tableName: "problem_status_history";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "problem_status_history";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const aiAnalyses: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "ai_analyses";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "ai_analyses";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        problemId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "problem_id";
            tableName: "ai_analyses";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        provider: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "provider";
            tableName: "ai_analyses";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        model: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "model";
            tableName: "ai_analyses";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        summary: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "summary";
            tableName: "ai_analyses";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        severityAssessment: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "severity_assessment";
            tableName: "ai_analyses";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        priorityRecommendation: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "priority_recommendation";
            tableName: "ai_analyses";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "low" | "medium" | "high" | "critical";
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: ["low", "medium", "high", "critical"];
            baseColumn: never;
        }, {}, {}>;
        categoryValidation: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "category_validation";
            tableName: "ai_analyses";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        evidenceAnalysis: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "evidence_analysis";
            tableName: "ai_analyses";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        duplicateFlag: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "duplicate_flag";
            tableName: "ai_analyses";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        duplicateConfidence: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "duplicate_confidence";
            tableName: "ai_analyses";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        missingInformation: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "missing_information";
            tableName: "ai_analyses";
            dataType: "json";
            columnType: "PgJsonb";
            data: string[];
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        confidenceScore: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "confidence_score";
            tableName: "ai_analyses";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        recommendedAction: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "recommended_action";
            tableName: "ai_analyses";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        rawResponse: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "raw_response";
            tableName: "ai_analyses";
            dataType: "json";
            columnType: "PgJsonb";
            data: unknown;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        completedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "completed_at";
            tableName: "ai_analyses";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "ai_analyses";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        updatedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "updated_at";
            tableName: "ai_analyses";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const aiResearchResults: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "ai_research_results";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "ai_research_results";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        problemId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "problem_id";
            tableName: "ai_research_results";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        backgroundInfo: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "background_info";
            tableName: "ai_research_results";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        possibleCauses: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "possible_causes";
            tableName: "ai_research_results";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        communityImpact: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "community_impact";
            tableName: "ai_research_results";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        relevantStatistics: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "relevant_statistics";
            tableName: "ai_research_results";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        similarIncidents: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "similar_incidents";
            tableName: "ai_research_results";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        potentialSolutions: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "potential_solutions";
            tableName: "ai_research_results";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        responsibleAuthority: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "responsible_authority";
            tableName: "ai_research_results";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        estimatedResolutionTime: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "estimated_resolution_time";
            tableName: "ai_research_results";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        completedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "completed_at";
            tableName: "ai_research_results";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "ai_research_results";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        updatedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "updated_at";
            tableName: "ai_research_results";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const researchSources: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "research_sources";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "research_sources";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        researchId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "research_id";
            tableName: "research_sources";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        title: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "title";
            tableName: "research_sources";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        url: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "url";
            tableName: "research_sources";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        summary: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "summary";
            tableName: "research_sources";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        relevanceScore: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "relevance_score";
            tableName: "research_sources";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "research_sources";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const civicReports: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "civic_reports";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "civic_reports";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        problemId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "problem_id";
            tableName: "civic_reports";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        overview: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "overview";
            tableName: "civic_reports";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        whyItMatters: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "why_it_matters";
            tableName: "civic_reports";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        researchFindings: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "research_findings";
            tableName: "civic_reports";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        severity: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "severity";
            tableName: "civic_reports";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        recommendedAction: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "recommended_action";
            tableName: "civic_reports";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        responsibleAuthority: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "responsible_authority";
            tableName: "civic_reports";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        proposedPostContent: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "proposed_post_content";
            tableName: "civic_reports";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        hashtags: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "hashtags";
            tableName: "civic_reports";
            dataType: "json";
            columnType: "PgJsonb";
            data: string[];
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        isAdminEdited: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "is_admin_edited";
            tableName: "civic_reports";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        adminEditedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "admin_edited_at";
            tableName: "civic_reports";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        adminEditedById: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "admin_edited_by_id";
            tableName: "civic_reports";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "civic_reports";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        updatedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "updated_at";
            tableName: "civic_reports";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const adminReviews: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "admin_reviews";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "admin_reviews";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        problemId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "problem_id";
            tableName: "admin_reviews";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        adminId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "admin_id";
            tableName: "admin_reviews";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        action: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "action";
            tableName: "admin_reviews";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        notes: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "notes";
            tableName: "admin_reviews";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        priorityOverride: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "priority_override";
            tableName: "admin_reviews";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "low" | "medium" | "high" | "critical";
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: ["low", "medium", "high", "critical"];
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "admin_reviews";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const notifications: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "notifications";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "notifications";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        userId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "user_id";
            tableName: "notifications";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        problemId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "problem_id";
            tableName: "notifications";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        type: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "type";
            tableName: "notifications";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "approved" | "published" | "resolved" | "status_change" | "ai_complete" | "admin_new_problem" | "admin_critical" | "admin_failed_publish" | "info_requested";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: ["status_change", "ai_complete", "approved", "published", "resolved", "admin_new_problem", "admin_critical", "admin_failed_publish", "info_requested"];
            baseColumn: never;
        }, {}, {}>;
        title: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "title";
            tableName: "notifications";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        message: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "message";
            tableName: "notifications";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        isRead: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "is_read";
            tableName: "notifications";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "notifications";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const publishingJobs: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "publishing_jobs";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "publishing_jobs";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        problemId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "problem_id";
            tableName: "publishing_jobs";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        triggeredById: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "triggered_by_id";
            tableName: "publishing_jobs";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        platforms: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "platforms";
            tableName: "publishing_jobs";
            dataType: "json";
            columnType: "PgJsonb";
            data: string[];
            driverParam: unknown;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        status: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "status";
            tableName: "publishing_jobs";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "publishing" | "published" | "pending" | "failed" | "skipped";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: ["pending", "publishing", "published", "failed", "skipped"];
            baseColumn: never;
        }, {}, {}>;
        startedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "started_at";
            tableName: "publishing_jobs";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        completedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "completed_at";
            tableName: "publishing_jobs";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "publishing_jobs";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const publishingResults: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "publishing_results";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "publishing_results";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        jobId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "job_id";
            tableName: "publishing_results";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        problemId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "problem_id";
            tableName: "publishing_results";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        platform: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "platform";
            tableName: "publishing_results";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "linkedin" | "facebook" | "instagram" | "twitter" | "wordpress" | "webhook";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: ["linkedin", "facebook", "instagram", "twitter", "wordpress", "webhook"];
            baseColumn: never;
        }, {}, {}>;
        status: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "status";
            tableName: "publishing_results";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "publishing" | "published" | "pending" | "failed" | "skipped";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: ["pending", "publishing", "published", "failed", "skipped"];
            baseColumn: never;
        }, {}, {}>;
        publishedUrl: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "published_url";
            tableName: "publishing_results";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        errorMessage: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "error_message";
            tableName: "publishing_results";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        retryCount: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "retry_count";
            tableName: "publishing_results";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        publishedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "published_at";
            tableName: "publishing_results";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "publishing_results";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        updatedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "updated_at";
            tableName: "publishing_results";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const duplicateFlags: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "duplicate_flags";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "duplicate_flags";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        problemId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "problem_id";
            tableName: "duplicate_flags";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        potentialDuplicateId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "potential_duplicate_id";
            tableName: "duplicate_flags";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        confidenceScore: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "confidence_score";
            tableName: "duplicate_flags";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        reason: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "reason";
            tableName: "duplicate_flags";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        resolvedByAdminId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "resolved_by_admin_id";
            tableName: "duplicate_flags";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        resolution: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "resolution";
            tableName: "duplicate_flags";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "duplicate_flags";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        resolvedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "resolved_at";
            tableName: "duplicate_flags";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export type ProblemCategory = typeof problemCategories.$inferSelect;
export type ProblemType = typeof problemTypes.$inferSelect;
export type Problem = typeof problems.$inferSelect;
export type ProblemLocation = typeof problemLocations.$inferSelect;
export type ProblemAttachment = typeof problemAttachments.$inferSelect;
export type ProblemStatusHistory = typeof problemStatusHistory.$inferSelect;
export type AiAnalysis = typeof aiAnalyses.$inferSelect;
export type AiResearchResult = typeof aiResearchResults.$inferSelect;
export type ResearchSource = typeof researchSources.$inferSelect;
export type CivicReport = typeof civicReports.$inferSelect;
export type AdminReview = typeof adminReviews.$inferSelect;
export type Notification = typeof notifications.$inferSelect;
export type PublishingJob = typeof publishingJobs.$inferSelect;
export type PublishingResult = typeof publishingResults.$inferSelect;
export type DuplicateFlag = typeof duplicateFlags.$inferSelect;
